name: vigenesia
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  dio: ^5.7.0
  another_flushbar: ^1.12.30
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.11
  http: ^1.2.2
  curved_navigation_bar: ^1.0.1
  flutter_form_builder: ^9.5.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
        - asset: assets/fonts/montserrat_bold.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/lato_regular.ttf
        - asset: assets/fonts/lato_bold.ttf
  assets:
    - assets/images/
